name: Handle Deployment

on:
  workflow_call:
    secrets:
      AWS_LAMBDA_PERMISSIONS:
        required: true   # OIDC role for GitHub Actions to assume
      DEPLOY_LAMBDA_PERMISSIONS:
        required: true   # Policy ARN to attach to Lambda exec role
      EVENTBRIDGE_SCHEDULER:
        required: true   # Scheduler ARN or ARN pattern
      LAMBDA_EXEC_ROLE_V3:
        required: true   # Lambda execution role ARN
      LAMBDA_FUNCTION_ARN:
        required: true   # Lambda function ARN

jobs:
  call-pylint:
    uses: ./.github/workflows/lint.yml

jobs:
  call-pylint:
    uses: ./.github/workflows/lint.yml

  call-deploy-invoke:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Dev' }}
    uses: ./.github/workflows/deploy_lambda.yml
    secrets:
      AWS_LAMBDA_PERMISSIONS: ${{ github.ref == 'refs/heads/main' && secrets.AWS_LAMBDA_PERMISSIONS_PROD || secrets.AWS_LAMBDA_PERMISSIONS }}
      DEPLOY_LAMBDA_PERMISSIONS: ${{ github.ref == 'refs/heads/main' && secrets.DEPLOY_LAMBDA_PERMISSIONS_PROD || secrets.DEPLOY_LAMBDA_PERMISSIONS }}
      EVENTBRIDGE_SCHEDULER: ${{ github.ref == 'refs/heads/main' && secrets.EVENTBRIDGE_SCHEDULER_PROD || secrets.EVENTBRIDGE_SCHEDULER }}
      LAMBDA_EXEC_ROLE_V3: ${{ github.ref == 'refs/heads/main' && secrets.LAMBDA_EXEC_ROLE_V3_PROD || secrets.LAMBDA_EXEC_ROLE_V3 }}
      LAMBDA_FUNCTION_ARN: ${{ github.ref == 'refs/heads/main' && secrets.LAMBDA_FUNCTION_ARN_PROD || secrets.LAMBDA_FUNCTION_ARN }}

