name: Lint with Pylint

on:
  workflow_call:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pytest

      - name: Run Pylint on all Python files
        run: |
          py_files=$(find . -type f -name "*.py")
          if [ -n "$py_files" ]; then
            pylint \
              --init-hook "import sys, os; sys.path.extend([os.path.abspath(os.path.dirname(f)) for f in sys.argv[1:]])" \
              $py_files
          else
            echo "No Python files found."
          fi


      - name: Run Tests
        run: |
          echo "Checking available .py files:"
          find . -name "*.py"
          
          echo "Running pytest with verbose output:"
          pytest -v
